### ISSUE TITLE
Pause menu buttons don't work

### ISSUE THREAD

**Issue by Hexagon-Dev** [3elDU/bamboo#4]
After window was resized to fullscreen, buttons in pause menu aren't clickable.
Sometimes if window is not maximized and several clicks were done - button works.

**Comment by Hexagon-Dev** [comment]
Btw, sometimes if window is not maximized and several clicks were done - button works.

**Comment by 3elDU** [comment]
Tried reproducing on macOS. Tried different window sizes. Couldn't reproduce.
Could this be windows-specific bug?

**Comment by 3elDU** [comment]
Nevermind. This is reproducible, especially with lower scaling ( < 2.0 )
What I suspect is, with lower scaling, the framerate gets low ( because there are more and more chunks to render ).
Ticks are skipped, and the button doesn't register clicks because of this.
